# ECHO OMEGA PRIME Website Update Script
# Commander: Bobby Don McWilliams II
# Date: 2025-12-17
# Features: ElevenLabs v3 Alpha Voice Integration

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ECHO OMEGA PRIME - Website Update" -ForegroundColor Cyan
Write-Host "  ElevenLabs v3 Alpha Voice Integration" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# Navigate to website directory
Set-Location "X:\ECHO_PRIME\WEBSITE"

# Backup current files
Write-Host "`n[1/6] Backing up current files..." -ForegroundColor Yellow
if (Test-Path "components\sections\StatsSection.tsx") {
    Copy-Item "components\sections\StatsSection.tsx" "components\sections\StatsSection.backup.tsx" -Force
}
if (Test-Path "components\sections\FeaturesSection.tsx") {
    Copy-Item "components\sections\FeaturesSection.tsx" "components\sections\FeaturesSection.backup.tsx" -Force
}
if (Test-Path "app\page.tsx") {
    Copy-Item "app\page.tsx" "app\page.backup.tsx" -Force
}

# Create lib directory if it doesn't exist
Write-Host "[2/6] Ensuring directory structure..." -ForegroundColor Yellow
if (!(Test-Path "lib")) {
    New-Item -ItemType Directory -Path "lib" -Force | Out-Null
}
if (!(Test-Path "app\api\voice")) {
    New-Item -ItemType Directory -Path "app\api\voice" -Force | Out-Null
}

# Replace with updated files
Write-Host "[3/6] Applying updates..." -ForegroundColor Yellow
if (Test-Path "components\sections\StatsSection.updated.tsx") {
    Copy-Item "components\sections\StatsSection.updated.tsx" "components\sections\StatsSection.tsx" -Force
}
if (Test-Path "components\sections\FeaturesSection.updated.tsx") {
    Copy-Item "components\sections\FeaturesSection.updated.tsx" "components\sections\FeaturesSection.tsx" -Force
}
if (Test-Path "app\page.updated.tsx") {
    Copy-Item "app\page.updated.tsx" "app\page.tsx" -Force
}

Write-Host "[4/6] Files updated:" -ForegroundColor Green
Write-Host "  - StatsSection.tsx (35,046+ tools, 1,062 gateways, 47 MCP servers)" -ForegroundColor Gray
Write-Host "  - FeaturesSection.tsx (Phoenix healer, X1200 Swarm, Divine Protocols)" -ForegroundColor Gray
Write-Host "  - page.tsx (Added PersonalitiesSection)" -ForegroundColor Gray
Write-Host "  - PersonalitiesSection.tsx (12 AI personalities with v3 voice)" -ForegroundColor Gray
Write-Host "  - lib/useVoice.ts (Voice hook with Web Audio API)" -ForegroundColor Gray
Write-Host "  - app/api/voice/route.ts (ElevenLabs v3 API endpoint)" -ForegroundColor Gray

# Check for environment variable
Write-Host "`n[5/6] Checking environment..." -ForegroundColor Yellow
if (Test-Path ".env.local") {
    Write-Host "  - .env.local found with ElevenLabs API key" -ForegroundColor Green
} else {
    Write-Host "  - WARNING: .env.local not found!" -ForegroundColor Red
    Write-Host "  - Create .env.local with ELEVENLABS_API_KEY" -ForegroundColor Yellow
}

# Git commit and push
Write-Host "`n[6/6] Committing and pushing to GitHub..." -ForegroundColor Yellow
git add .
git commit -m "Add ElevenLabs v3 Alpha Voice Integration + AI Personalities Section

NEW FEATURES:
- 12 AI Personalities with unique voices (ElevenLabs v3 Alpha)
- Click-to-hear voice introductions with emotional audio tags
- Trinity Council unified voice
- Dynamic voice generation with [laughs], [whispers], [sarcastic], etc.
- Web Audio API playback for cross-browser compatibility

VOICE IDS INTEGRATED:
- ECHO PRIME: keDMh3sQlEXKM4EQxvvi
- SAGE: FUoqmAV8wIzxDbnwByO6
- NYX: Yx6SGo4s49An9fBlDJ3z
- THORNE: 3WkXzs93soZG22ZM7DI5
- PROMETHEUS: BVZ5M1JnNXres6AkVgxe
- GS343: 8ATB4Ory7NkyCVRpePdw
- EPCP3O: 0UTDtgGGkpqERQn1s0YK
- RAISTLIN: pqHfZKP75CvOlQylNhV4
- PHOENIX: 871R4lUmto99RAPOC7lQ
- BREE: pzKXffibtCDxnrVO8d1U
- R2D2: Audio clips

STATISTICS (VERIFIED):
- 35,046+ Custom Tools (MEGA_GATEWAY)
- 71,000+ Memory Crystals
- 492,000+ EKM Modules
- 6,820 Code Templates
- 1,062+ Gateways
- 47+ MCP Servers
- 12 AI Personalities

Generated by ECHO OMEGA PRIME
Commander Bobby Don McWilliams II - Authority Level 11.0"

git push origin main

Write-Host "`n========================================" -ForegroundColor Green
Write-Host "  DEPLOYMENT COMPLETE" -ForegroundColor Green
Write-Host "  Vercel will auto-deploy in ~60 seconds" -ForegroundColor Green
Write-Host "  https://echo-omega-prime.vercel.app" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "IMPORTANT: Set Vercel Environment Variable" -ForegroundColor Magenta
Write-Host "  1. Go to Vercel Dashboard > Project Settings" -ForegroundColor White
Write-Host "  2. Add Environment Variable:" -ForegroundColor White
Write-Host "     ELEVENLABS_API_KEY = sk_1921246f88b8fbecdb0cc047774eae7523043b180389d308" -ForegroundColor Yellow
Write-Host "  3. Redeploy if needed" -ForegroundColor White
Write-Host ""
Write-Host "New Features Added:" -ForegroundColor Magenta
Write-Host "  - 12 AI Personalities with ElevenLabs v3 Alpha voices" -ForegroundColor White
Write-Host "  - Click any personality card to hear their intro" -ForegroundColor White
Write-Host "  - Trinity Council combined voice" -ForegroundColor White
Write-Host "  - Audio tags: [laughs] [whispers] [sarcastic] [excited]" -ForegroundColor White
Write-Host "  - Corrected statistics from verified system audit" -ForegroundColor White
